name: Run Discord Bot

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      
      # 1. Registra los comandos en la API de Discord
      - run: node deploy-commands.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}

      # 2. Inicia el bot
      - run: node index.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
